In [ ]:
# Urban Heat Mitigation
# Model Experiments

# Goal:
# Compare Linear Regression and Random Forest
# for predicting Land Surface Temperature (LST)

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
df = pd.read_csv("../data/processed/final_dataset.csv")

df.head()

         LST      NDBI      NDVI   Latitude  Longitude
0  31.156284  0.031976  0.253471  23.271867  77.362780
1  31.349402  0.102853  0.112366  23.182363  77.455041
2  29.766859 -0.065514  0.493861  23.232723  77.494086
3  31.711712  0.019941  0.295933  23.330404  77.440537
4  34.456382  0.108726  0.362501  23.212105  77.405127

In [3]:
X = df[
    [
        "NDVI",
        "NDBI",
        "Latitude",
        "Longitude"
    ]
]

y = df["LST"]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [5]:
lr = LinearRegression()

lr.fit(X_train, y_train)

lr_predictions = lr.predict(X_test)

lr_mae = mean_absolute_error(
    y_test,
    lr_predictions
)

lr_rmse = mean_squared_error(
    y_test,
    lr_predictions
) ** 0.5

lr_r2 = r2_score(
    y_test,
    lr_predictions
)

print("Linear Regression")
print("MAE :", lr_mae)
print("RMSE:", lr_rmse)
print("R2  :", lr_r2)

Linear Regression
MAE : 1.3792347649020789
RMSE: 1.7561312112001533
R2  : 0.5709707379575865

In [6]:
rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

rf_predictions = rf.predict(X_test)

rf_mae = mean_absolute_error(
    y_test,
    rf_predictions
)

rf_rmse = mean_squared_error(
    y_test,
    rf_predictions
) ** 0.5

rf_r2 = r2_score(
    y_test,
    rf_predictions
)

print("Random Forest")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2  :", rf_r2)

Random Forest
MAE : 1.1540547612427485
RMSE: 1.4757429127991766
R2  : 0.697033643787542

In [7]:
comparison = pd.DataFrame(
    {
        "Model": [
            "Linear Regression",
            "Random Forest"
        ],
        "MAE": [
            lr_mae,
            rf_mae
        ],
        "RMSE": [
            lr_rmse,
            rf_rmse
        ],
        "R2": [
            lr_r2,
            rf_r2
        ]
    }
)

comparison

               Model       MAE      RMSE        R2
0  Linear Regression  1.379235  1.756131  0.570971
1      Random Forest  1.154055  1.475743  0.697034

In [ ]:
## Conclusion

Two machine learning models were evaluated for Land Surface Temperature prediction.

- Linear Regression was used as the baseline model.
- Random Forest achieved better performance.
- Random Forest captured non-linear relationships between NDVI, NDBI and LST more effectively.

Therefore, Random Forest was selected as the final model for the Urban Heat Mitigation system.